In [1]:
import numpy as np
from datetime import date, timedelta

# **1. Create a 3x3x3 array with random values**

In [2]:
arr = np.random.rand(3,3,3)
arr

array([[[0.01713918, 0.50433053, 0.30437839],
        [0.28136272, 0.19818382, 0.70264682],
        [0.47734007, 0.52856228, 0.73965223]],

       [[0.42776426, 0.49036654, 0.26438971],
        [0.20936002, 0.80768449, 0.19488585],
        [0.20690345, 0.82188475, 0.12372167]],

       [[0.79747717, 0.16418161, 0.73140868],
        [0.40146436, 0.76089466, 0.94547671],
        [0.69524731, 0.35797041, 0.19064175]]])

# **2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [6]:
arr = np.diag(np.arange(4)+1 , k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# **3.Create a 8x8 matrix and fill it with a checkerboard pattern**

In [8]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# **4. Normalize a 5x5 random matrix**

In [9]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[ 0.0679168 ,  1.19797408,  1.13463639,  1.18906319, -0.36423635],
       [-0.76161799, -0.21852251, -1.389117  , -0.45338203,  1.16187701],
       [ 0.40456395,  0.05148929,  0.53650559,  0.70824836,  1.39774805],
       [-1.16353254, -1.22097514, -1.07130336,  1.30116238,  1.34863703],
       [-0.65080439,  0.73689892, -1.18688243, -1.49164157, -1.26470574]])

# **5.  How to find common values between two arrays?**

In [10]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

np.intersect1d(arr1, arr2)

array([1, 2, 4, 6])

# **6.How to get the dates of yesterday, today and tomorrow?**

In [12]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("yesterday Time: ",yesterday)
print("today Time:     ",today)
print("tomorrow Time:  ",tomorrow)


yesterday Time:  2020-07-27
today Time:      2020-07-28
tomorrow Time:   2020-07-29


# **7. Consider two random array A and B, check if they are equal**

In [13]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.67151811 0.20680662 0.56900476]
 [0.20244281 0.5944365  0.23915182]
 [0.97260112 0.79050812 0.61349367]]


Array2:
[[0.95560109 0.82331842 0.05556609]
 [0.51024521 0.08886215 0.57837068]
 [0.22945404 0.5423198  0.81555241]]


Equality: False


# **8.Create random vector of size 10 and replace the maximum value by 0**

In [14]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.67410993, 0.21206245, 0.85267804, 0.        , 0.45845569,
       0.6671362 , 0.06935931, 0.598614  , 0.55293981, 0.39923086])

# **9. How to print all the values of an array?**

In [15]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# **10.Subtract the mean of each row of a matrix**

In [16]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean

array([[-0.24187721, -0.04365805,  0.28553526],
       [ 0.35095875,  0.16317743, -0.51413618],
       [ 0.19149167, -0.32722384,  0.13573216]])

# **11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?** 

In [17]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([3., 2., 3., 4., 3.])

# **12.How to get the diagonal of a dot product?**

In [18]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([86, 21, 39])

# **13.How to find the most frequent value in an array?**

In [19]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[7 5 7 4 2 6 7 1 0 6 8 3 8 5 5 4 0 5 9 6]


5

# **14.How to get the n largest values of an array**

In [20]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

9

# **15.How to create a record array from a regular array?**

In [21]:

arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])